---

- name: Creating working directory
  file: 
    path: "{{ ee_path }}"
    state: directory

- name: Copy config files to the working directory
  copy:
    src: "{{ item }}"
    dest: "{{ ee_path }}/{{ item }}"
  with_items:
    - ansible.cfg
    - execution-environment.yml
    - requirements.yml
    - requirements.txt
    - bindep.txt
  become: yes

- name: Run ansible-builder command
  command:
    cmd: "{{ ansible_builder_cmd }}"
    chdir: "{{ ee_path }}"
  become: yes

- name: Include vault quay.io credentials
  include_vars: ../vaults/vault_quay.yml

# - name: Remove all existing container images
#   ansible.builtin.command: podman rmi -af
#   changed_when: true
#   ignore_errors: true

- name: Login into quay.io registry
  containers.podman.podman_login:
    username: "{{ ee_registry_user }}"
    password: "{{ ee_registry_pass }}"
    registry: quay.io

- name: Push EE to quay.io registry
  containers.podman.podman_image:
    name: ee-ansible-ssa
    push: true
    push_args:
      dest: "{{ ee_registry_url }}"
