---

- name: Creating working directory
  file: 
    path: "{{ ee_path }}"
    state: directory

- name: Copy config files to the working directory
  copy:
    src: "{{ item }}"
    dest: "{{ ee_path }}/{{ item }}"
  with_items:
    - ansible.cfg
    - execution-environment.yml
    - requirements.yml
    - requirements.txt
    - bindep.txt
  become: yes
  
- name: Install ansible-builder
  pip:
    name: ansible-builder
    state: present
  #become: yes

# - name: Install python-dnf
#   pip:
#     name: python-dnf
#     state: present

- name: Install podman
  dnf:
    name: podman
    state: present
#   vars:
#     ansible_python_interpreter: /usr/libexec/platform-python

- name: Run ansible-builder command
  command:
    cmd: "{{ ansible_builder_cmd }}"
    #cmd: "mkdir {{ ee_image }}1"
    chdir: "{{ ee_path }}"

- name: Push image to image registry
  command: 
    #cmd: "{{ ee_registry_cmd }}"
    cmd: "mkdir {{ ee_image }}2"
    chdir: "{{ ee_path }}"

