---

#- name: Podman garbage collection on any old containers *will clear out most contianers*
#  ansible.builtin.shell: sudo podman system prune -a -f
#  changed_when: false

- name: Run ansible-builder command
  ansible.builtin.command: 
    #cmd: "{{ ansible_builder_cmd }}"
    cmd: "mkdir {{ ee_image }}1"
    chdir: "{{ ee_path }}"

- name: Push image to image registry
  ansible.builtin.command: 
    #cmd: "{{ ee_registry_cmd }}"
    cmd: "mkdir {{ ee_image }}2"
    chdir: "{{ ee_path }}"
