---

#- name: Podman garbage collection on any old containers *will clear out most contianers*
#  ansible.builtin.shell: sudo podman system prune -a -f
#  changed_when: false

- name: Creating working directory
  file: 
    path: "{{ ee_path }}"
    state: directory

- name: LS
  command: 
    cmd: "whereis ansible-builder"

- name: LS
  command: 
    cmd: "ls /root/"

- name: LS
  command: 
    cmd: "ls $HOME"

- name: Copy config files to the working directory
  copy:
    src: "{{ item }}"
    dest: "{{ ee_path }}/{{ item }}"
  with_items:
    - ansible.cfg
    - execution-environment.yml
    - requirements.yml
    - requirements.txt
    - bindep.txt
  become: yes
  
- name: Install ansible-builder
  pip:
    name: ansible-builder
  #become: yes

# - name: Install python3 pip
#   yum:
#     name: python3-pip
#     state: present
#   become: yes

- name: Set up ansible-builder
  shell: | 
    echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.profile
    source ~/.profile
    python3 -m pip install ansible-builder --user
    exit 0
#  become: yes
  
- name: Run ansible-builder command
  command:
    cmd: "{{ ansible_builder_cmd }}"
    #cmd: "mkdir {{ ee_image }}1"
    chdir: "{{ ee_path }}"

- name: Push image to image registry
  command: 
    #cmd: "{{ ee_registry_cmd }}"
    cmd: "mkdir {{ ee_image }}2"
    chdir: "{{ ee_path }}"
