---

#- name: Podman garbage collection on any old containers *will clear out most contianers*
#  ansible.builtin.shell: sudo podman system prune -a -f
#  changed_when: false

- name: Creating working directory
  file: 
    path: "mkdir {{ ee_path }}"
    state: directory

- name: PWD
  command:
    cmd: pwd
    
- name: LS
  command:
    cmd: ls -la
    
- name: Copy config files to the working directory
  copy:
    src: "{{ item }}"
    dest: "{{ ee_path }}{{ item }}"
  with_items:
    - ansible.cfg
    - execution-environment.yml
    - requirements.yml
    - requirements.txt
    - bindep.txt

- name: Run ansible-builder command
  command:
    #cmd: "{{ ansible_builder_cmd }}"
    cmd: "mkdir {{ ee_image }}1"
    chdir: "{{ ee_path }}"

- name: Push image to image registry
  command: 
    #cmd: "{{ ee_registry_cmd }}"
    cmd: "mkdir {{ ee_image }}2"
    chdir: "{{ ee_path }}"
